FinMind/FinMind

- README.md
> Revert "fixed readme grammar"

- .gitignore
- dataset.md
- example/Python document.md
- example/R document.md
- example/api_demo.py
- add GovernmentBondsYield Python doc
- add GovernmentBondsYield R doc
- add GovernmentBondsYield dataset
- add GovernmentBondsYield api demo
> [ADD] GovernmentBondsYield dataset

- dataset.md
- example/Python document.md
- example/R document.md
- example/api_demo.py
- add TaiwanCashFlowsStatement api doc
- add RawMaterialFuturesPricesMinute  api doc
- add  TaiwanStockPriceMinute api doc
> Dev yc new dataset

- BackTesting/INSTITUTIONAL_INVESTORS_FOLLOWER.py
- BackTesting/KDCROSSOVER.py
- BackTesting/MACDCROSSOVER.py
- BackTesting/MACROSSOVER.py
- BackTesting/MAXMINPERIODBAIS.py
- BackTesting/SHORTSALE_MARGINPURCHASE_RATIO.py
- Add institutional investors strategy
- Add KD CROSSOVER strategy
- Add MACD CROSSOVER strategy
- Add MA CROSSOVER strategy
- Add MAX MIN PERIOD BAIS strategy
- Add SHORTSALE MARGINPURCHASE RATIO strategy
> Develop yc strategy

- README.md
> fix head link

- README.md
原先是寫死的，顯示為 MIT
但目前看專案其實是 Apache 2.0，所以幫忙更改了一下以便顯示正確的 LICENSE badge
如果願意接受並 merge 這個 PR 的話，請考慮幫忙加上 `hacktoberfest-accepted` 這個 label，幫助我參加 hacktoberfest；沒有的話也沒關係，本來重點就在修正文件內容 :)。
> Update README LICENSE badge

- Makefile
- 修復 package publish permission denied
> fix: package publish permission denied

- FinMind/BackTestSystem/__init__.py
> add:schema to module path

- FinMind/BackTestSystem/BaseClass.py
- FinMind/BackTestSystem/utils.py
- tests/BackTestSystem/test_strategies.py
> fix:sell action do not sell stock

- README.md
> Improve README a bit more

- README.md
> Center logo

- .github/workflows/python-package.yml
- FinMind/Data/Load.py
- Pipfile
- Pipfile.lock
- tests/BackTestSystem/test_strategies.py
- tests/Data/test_load.py
新增還原股價 
因為直接新增submodule覺得邏輯上怪怪的
就先跟data load 放在一起
之後再找時間把對api操作的部分抽象出來
還原股價的部分是跟隨histock and 玩股網算法 
測試2330與幾支金融股結果一致
測試採用玩股網2019/04/01價格做比對
https://www.wantgoo.com/stock/2330/technical-chart
https://histock.tw/stock/tchart.aspx?no=2330&m=unex
> Add retroactive price 

- FinMind/Data/Load.py
- tests/Data/test_load.py
> Fix retroactive spread error

- .coveragerc
- .github/workflows/python-package.yml
- Pipfile
- Pipfile.lock
> add:test coverage

- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
> Fix issue: remove suspension trading data

- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
#153 
A basic method to fix empty stock price dataframe. pass if stock price dataframe is empty.
> fix: taiwan_stock_daily_adj with empty data error

- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
改動如下
1. 增加 `stock_price["date"] = stock_price["date"].astype(str)`
> fix: taiwan_stock_daily_adj date type

- FinMind/data/data_loader.py
- FinMind/plotting/kline.py
- Makefile
- tests/data/test_data_loader.py
- tests/plotting/test_kline.py
> feat: add kline_margin_purchase_short_sale

- README.md
> feat: add kline doc

- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
**debug**
* 月營收日期輸入 2021-01-01 等日期，會掛掉
* add test case
> fix: data loader pd.Period convert

- FinMind/__init__.py
- FinMind/plotting/__init__.py
- FinMind/plotting/bar.py
- FinMind/plotting/kline.py
- FinMind/schema/__init__.py
- FinMind/schema/plot.py
- tests/plotting/test_bar.py
- tests/schema/test_plot.py
1. add bar plot
2. add BarPlotSchema
3. kline add filename param
```python
from FinMind import plotting
from FinMind.data import DataLoader
from FinMind.schema import BarPlotSchema
data_loader = DataLoader()
df = data_loader.taiwan_stock_month_revenue(
stock_id='2330', start_date='2020-1M', end_date='2021-7M'
)
df["labels"] = (
df[["revenue_year", "revenue_month"]]
.astype(str)
.agg(lambda date: f"{date[0]}-{date[1]}M", axis=1)
)
df["series"] = df["revenue"].agg(lambda value: round(value / 1e8, 2))
bar_plot_data = BarPlotSchema.df_convert(df)
plotting.bar(bar_plot_data, title='月營收', yaxis_color='orange')
```
```python
plotting.bar?
Signature:
plotting.bar(
bar_plot_data:FinMind.schema.plot.BarPlotSchema,
y_series_name:str='',
y_axis_name:str='億',
yaxis_color:str='#dca540', …
```
> feat: add bar plot

- FinMind/data/data_loader.py
- FinMind/schema/data.py
- tests/data/test_data_loader.py
https://github.com/FinMind/FinMind/issues/168
> feat: add TaiwanStockTotalReturnIndex

- FinMind/data/finmind_api.py
ref: 
- https://github.com/tweepy/tweepy/blob/68e19cc6b9b23d72369ca1520093770eb18a5a9f/tweepy/streaming.py#L251
- https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f
> feat: Handle connection errors

- FinMind/data/finmind_api.py
* fix: remove "msg" in response.json() not logger.error issue
> fix: remove "msg" in response.json() not logger.error issue

- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- .github/workflows/test-wheel.yml
- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
consider the reduction capital in taiwan_stock_daily_adj api
> 231 adj stock price need to consider capital reduction

- FinMind/data/data_loader.py
- FinMind/schema/data.py
- tests/data/test_data_loader.py
add the taiwan_stock_government_bank_buy_sell dataset
> add: taiwan_stock_government_bank_buy_sell dataset

- FinMind/data/data_loader.py
- tests/data/test_data_loader.py
change the start date to stock price min date in ex_dividend_price data
> Change the start date in ex_dividend_price data in taiwan_stock_daily_adj api

- FinMind/data/finmind_api.py
api 換版時會改變 response json 的資料，status 不會存在response json
避免package loging 有問題，status 改從 resp 直接獲取
> add: change the status code

- FinMind/data/data_loader.py
- FinMind/schema/data.py
- tests/data/test_data_loader.py
> add: tw 10 year avg close

- FinMind/data/finmind_api.py
https://github.com/FinMind/FinMind/issues/279
> feat: raise Exception on request_get

- FinMind/strategies/base.py
- tests/strategies/test_strategies.py
過去回測的除權息計算上，發生錯誤，少了把現金股利，加到交易資金中
> fix: backtest compute_div_income

- FinMind/data/finmind_api.py
- tests/data/test_finmind_api.py
> feat: add api_usage

- FinMind/data/data_loader.py
- FinMind/schema/data.py
- tests/data/test_data_loader.py
add TaiwanStockDispositionSecuritiesPeriod dataset
> add: TaiwanStockDispositionSecuritiesPeriod dataset

- FinMind/data/data_loader.py
- FinMind/schema/data.py
- tests/data/test_data_loader.py
add new dataset, TaiwanStockIndustryChain
> New data TaiwanStockIndustryChain
